### ISSUE TITLE
从master下载,执行yarn后,报kleur' do not define a valid './colors' target

### ISSUE THREAD

**Issue by macroswang** [javaLuo/react-admin#12]
ERROR in ./src/layouts/BasicLayout.less (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/less-loader/dist/cjs.js??ref--7-3!./src/layouts/BasicLayout.less)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Package exports for '/Users/wang/Desktop/react-admin/node_modules/kleur' do not define a valid './colors' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19

请问这是怎么回事？

**Comment by javaLuo** [comment]
你可能需要升级一下node.js,至少在10.12以上

**Comment by macroswang** [comment]
➜  ~ node -v
v13.5.0

是v13.5.0，这个问题我在google上去搜索都没结果，好奇怪

**Comment by macroswang** [comment]
我把nodejs升级到最新版本就可以了，感谢回复
